name: pairup
channels:
  - conda-forge
dependencies:
  - python=3.12.8
  - pip=24.2.0
  - pandas=2.2.3
  - python-dotenv=0.21.0
  - openpyxl=3.1.5
  - pip:
      - sqlalchemy==2.0.35
      - psycopg2-binary==2.9.10
      - pyxlsb==1.0.10
      - oracledb==3.1.0
      - pytest==8.3.5
